CREATE DATABASE IF NOT EXISTS minesweeper_db
  CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
USE sweeping_bomb;

CREATE TABLE player (
  player_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
) ENGINE=InnoDB;  

CREATE TABLE game_history (
  history_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  player_id INT UNSIGNED NOT NULL,
  score INT NOT NULL,
  played_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES player(player_id) ON DELETE CASCADE
) ENGINE=InnoDB;

